#!/bin/bash

echo " Script de compilação"
echo " By Pacman Pereira ...................... 2015 - 01 - 07"
echo "========================================================="
echo "           "
echo "                        O O O"
echo "                      O       O"
echo "                    O           O"
echo "                  O               O"
echo "                O                   O"
echo "                O                   O"
echo "               O  O               O  O"
echo "               O    O           O    O"
echo "               O      O       O      O"
echo "               O        O O O        O"
echo "               O          O          O"
echo "                 O        O        O"
echo "                   O      O      O"
echo "                     O    O    O"
echo "                       O  O  O"
echo "   _____                 OOO  ____"
echo "  |             ___     ___  |    |       ___  _     _"
echo "  |      |   | |   | | |     |    | |    |   |  |   |"
echo "  |      |   | |===  | |     |====  |    |   |   |_| "
echo "  |      |   | |   | | |     |    | |    |   |   | |"
echo "  |      |   | |   | | |     |    | |    |   |  |   |"
echo "   ^^^^^  ^^^   ^^^     ^^^   ^^^^   ^^^  ^^^  ^     ^"
echo "======================================================="
echo ""

gcc -o main main.c virtualscreen.c vector.c dda.c context.c

if [ $? -ne 0 ]
then
    echo "Compile failed!"
    exit 1
else
    echo "Compile succeeded without warnings"
fi
